nats-io/nsc

cmd/defaults.go

Not strictly true, but avoids double update (user can use update)

Minor fix to update, default time to current time

---

cmd/accountcontextparams.go
cmd/addaccount.go
cmd/addcluster.go
cmd/addexport_test.go
cmd/addimport_test.go
cmd/adduser_test.go
cmd/clustercontextparams.go
cmd/clustercontextparams_test.go
cmd/contextconfig.go
cmd/contextconfig_test.go
cmd/defaults.go
cmd/deleteexport_test.go
cmd/deleteimport_test.go
cmd/describeaccount_test.go
cmd/describecluster_test.go
cmd/editaccount_test.go
cmd/editcluster_test.go
cmd/editserver_test.go
cmd/edituser_test.go
cmd/env.go
cmd/generateactivation_test.go
cmd/generateconfig_test.go
cmd/store/store.go
cmd/util_test.go

Regardless of the current setting for default account/cluster, handle the
--account/--cluster flags correctly.
Adding an account or cluster will now set that account/cluster as a default
as reported by `nsc env`. Commands that specify an `--account/cluster` will
use the value transiently.

Fix for commands that specify --account or --cluster 

---

cmd/addaccount_test.go
cmd/addclustert_test.go
cmd/addexport_test.go
cmd/addimport_test.go
cmd/addserver_test.go
cmd/adduser_test.go
cmd/common.go
cmd/defaults.go
cmd/defaults_test.go
cmd/deleteexport_test.go
cmd/deleteimport_test.go
cmd/editaccount.go
cmd/generateactivation_test.go
cmd/signer.go
cmd/store/keys.go
cmd/util_test.go

[CHANGE] signer functionality (-K) on interactive will always prompt for path/key on non-managed stores.
[CHANGE] signer params interactive will never prompt to generate a key, since signing keys should pre-exist
[CHANGE] signer params will show default or set value (-K) when prompting
[ADD] KeyStore functionality to return the path where a key is expected

Normalize interactions requesting for signer keys

---

cmd/common_test.go
cmd/generateserverconfig.go
cmd/memresolverconfigbuilder.go
cmd/memresolverconfigbuilder_test.go
cmd/nkeyconfigbuilder.go
cmd/nkeyconfigbuilder_test.go
cmd/replytool.go
cmd/reqtool.go
cmd/subtool.go
cmd/tools_test.go
go.mod
go.sum
vendor/github.com/nats-io/nats-server/v2/server/client.go
vendor/github.com/nats-io/nats-server/v2/server/const.go
vendor/github.com/nats-io/nats-server/v2/server/jwt.go
vendor/github.com/nats-io/nats-server/v2/server/leafnode.go
vendor/github.com/nats-io/nats-server/v2/server/monitor.go
vendor/github.com/nats-io/nats-server/v2/server/opts.go
vendor/github.com/nats-io/nats-server/v2/server/reload.go
vendor/github.com/nats-io/nats-server/v2/server/route.go
vendor/github.com/nats-io/nats-server/v2/server/server.go
vendor/modules.txt

Also implemented a hidden mode where the config references jwt files - requires server support.
usage on nsc is always available from nsc --help or by drilling:
```bash
nsc add operator -n O
nsc edit operator --service-url nats://localhost:4222
nsc add account -n A
nsc add user -n aa
nsc add account -n B
nsc add user -n bb
nsc generate config --mem-resolver --config-file /tmp/server.conf
```
On another terminal:
```bash
nats-server -c /tmp/server.conf
```
On another terminal:
```bash
nsc sub foo
```
On yet another:
```bash
nsc pub foo
```

implemented inline jwts for operator, this simplifies generate config.

---

cmd/generateserverconfig.go
cmd/memresolverconfigbuilder.go
cmd/memresolverconfigbuilder_test.go
cmd/nkeyconfigbuilder.go

```
nsc add operator -n O
nsc add account -n SYS
nsc add user -n sys
nsc add account -n A
nsc generate config --mem-resolver --sys-account SYS
...
system_account: AAYTMQXD2ZS56IXBRKB2VHMRXL5OXWSUNYOIHWGSN2Q7X5F4JSMMZKR6
...
```

added ability to specify system account when generating mem-resolver configuration.

---

cmd/addaccount_test.go
cmd/addexport_test.go
cmd/addimport_test.go
cmd/adduser_test.go
cmd/common.go
cmd/deleteimport_test.go
cmd/generateactivation_test.go
cmd/signerparams.go
cmd/store/store.go

- present the user with a picker of all the keys we know we have
- if some keys are missing, provide an 'other' option
- validate that the entered key matches a signer public key

modified signer params to:

---

cmd/describe.go
cmd/describeoperator_test.go
cmd/describer.go
cmd/friendlynamecollector.go
cmd/friendlynamecollector_test.go
cmd/root.go
cmd/util_test.go

Describing an account shows import source accounts as simple names

Added friendly names to account imports

---

cmd/editoperator.go

Fixed an issue where editing an operator didn't required the main key to be present to sign the edits - The editor never prompted for the key to sign it.

interactive operator edit didn't prompt for signing key

---

cmd/init.go
cmd/init_test.go

new implementation only takes two options, 'name' and 'url', and creates an operator, account, and user using the specified name. If url is provided, it also deploys the created account to the specified url.

replaced init command with a simpler implementation

---

.travis.yml
cli/testprompts.go
cmd/accountcontextparams.go
cmd/addaccount.go
cmd/addaccount_test.go
cmd/addexport.go
cmd/addexport_test.go
cmd/addoperator.go
cmd/addoperator_test.go
cmd/adduser_test.go
cmd/common.go
cmd/deleteexport_test.go
cmd/deploy_test.go
cmd/push.go
cmd/push_test.go
cmd/revokeuser_test.go
cmd/signerparams.go
cmd/signerparams_test.go
cmd/store/store.go
cmd/util_test.go

Typical operations in NSC require a signer that is locally available. To support a managed operator, the signer will never be available. Support for a managed operator is baked into the JWT via its Account Server URL field.
A managed operator accepts a self-signed account JWT on an account JWT server and re-signs it with the operator key.
The change for supporting a managed operator, the store function will check if the operator is managed, if it is, it will push the account JWT to the account server defined by the operator (a requirement for a managed operator). If pushed succeeds, it then queries the operator for the JWT which is now signed by the operator (with limits injected). The signed JWT is then stored on disk.
It is possible for an operator to accept an account (where additional …

support managed operators

---

cmd/addoperator_test.go
cmd/adduser.go
cmd/contextconfig.go
cmd/defaults.go
cmd/defaults_test.go
cmd/env.go
cmd/store/store.go

modified tool to be cwd aware
- if the cwd is a directory that immediately has an operator under it, the stores dir is set to it
- if the cwd is a sub directory belonging to an operator, the stores dir is set to the operator's parent dir
- anywhere else, uses the set preference

cwd awareness

---

cmd/addoperator.go
cmd/init.go
cmd/wellknownoperator.go
cmd/wellknownoperator_test.go

if the operator name is well-known, we override to the name specified by the well-known operator.

Added a reverse lookup for the operator name -

---

cmd/keycollector.go

Removed a validation that prevented listing operator keys if no accounts are available.

FIX unable to list operator keys when no accounts available.

---

Makefile
cmd/describe.go
cmd/describeaccount.go
cmd/describeaccount_test.go
cmd/describeoperator.go
cmd/describeoperator_test.go
cmd/describeuser.go
cmd/describeuser_test.go
cmd/store/store.go

Added the ability to describe an operator, account or user in raw format. This allows the user to easily copy JWT formatted string for other purposes.

describe entity as a "raw" jwt 

---

cmd/rtttool.go
cmd/tool.go

The Go client behaves differently than the node client. So disconnect events are fired on close.
Changed disconnect/close handlers on the tools to check the status of the client, and thus avoid spurious disconnect/close messages.

Disconnect/Close handlers print spurious messages on the tools depending on timing.

---

cmd/migrate.go
cmd/migrate_test.go

The migrate command needs to self-sign accounts before pushing to the remote server, or the account server will reject them.

Self-sign migrate

---

cmd/exportkeys.go
cmd/exportkeys_test.go
cmd/generatenkey.go
cmd/importkeys.go
cmd/keycollector.go
cmd/listkeys.go
cmd/listkeys_test.go
cmd/migrate.go
cmd/root.go

The action framework requires a store to be set. In some cases such as dealing with the keystore, it should be ok not to have it, the example is migrating from ngs. The store may not exist, but the keys do.

FIX #180 - Allowed some commands (keys) to execute even if no store is set

---

cmd/addaccount.go
cmd/addaccount_test.go
cmd/addoperator.go
cmd/addoperator_test.go
cmd/adduser.go
cmd/adduser_test.go
cmd/common.go
cmd/common_test.go
cmd/describeaccount.go
cmd/describeoperator.go
cmd/describeuser.go
cmd/describeuser_test.go
cmd/editaccount.go
cmd/editaccount_test.go
cmd/editoperator.go
cmd/edituser.go
cmd/edituser_test.go

changed commands that add/edit/describe to accept an extra argument as the '--name' argument.
This makes it possible to `nsc add account A` which is more natural if a bit ambiguous.

FIX #47  change add/edit/describe to allow extra argument as '--name'

---

cmd/store/status.go
cmd/store/status_test.go

server messages, those messages are shown.

Collapsing status hid server messages. Now if a child status contains

---

cmd/addimport.go
cmd/addimport_test.go
cmd/describer.go

FIX #203 - stream imports can have empty prefixes
Fixed imports from local accounts to correctly handle public services
Fixed import table header say "Local/Prefix" on import describers

fix stream imports to allow empty prefixes for streams

---

cmd/addexport_test.go
cmd/addimport.go
cmd/cmd_test.go
cmd/deleteexport.go
cmd/deleteimport.go
cmd/deleteimport_test.go
cmd/importcollector.go
go.mod
go.sum
vendor/github.com/nats-io/jwt/account_claims.go
vendor/github.com/nats-io/jwt/creds_utils.go
vendor/github.com/nats-io/jwt/exports.go
vendor/github.com/nats-io/jwt/header.go
vendor/github.com/nats-io/jwt/imports.go
vendor/github.com/nats-io/jwt/operator_claims.go
vendor/modules.txt

- on interactive streams are rendered with `-> subject` and services with `<- subject`
- add import flag `--local-subject` changed description as 'local subject or prefix'
- stream imports no longer force a prefix
- removed `--service` flag from delete import - the unique identifier is the remote subject
- for non interactive imports delete, if the subject has multiple matches, `--src-account` with account key is required

changes to normalize and make it easier to select imports/exports when deleting them

---

cmd/addimport.go
cmd/addimport_test.go
cmd/nkeyconfigbuilder_test.go

- imports from activations without interactive were setting prefix for streams
- parsing of the token didn't always strip decorations.

FIX #210 - activation import fixes

---

cmd/addimport.go
cmd/generateactivation.go
cmd/generateactivation_test.go
cmd/util_test.go
go.mod

FIX #215 - export selection is single list
FIX #211 - added `--push` to push the activation to the account server

Push activations to account server

---

cmd/adduser.go

FIX #236 - the output file flag was added but it was never supported.

removed flag 'output-file' as the command doesn't render the configuration

---

cmd/deleteaccount.go
cmd/deleteaccount_test.go

Options are provided to revoke and delete nkeys and creds files for the entities. When an account is deleted, the JWT is set to expire 1m after. This allows an account server to reject any other user in the wild.

Added delete account. Deleting an account also deletes its users.

---

.goreleaser.yml

added goreleaser configuration for pushing a tap to github.com/nats-io/homebrew-nats-tools.
to install from homebrew, after the tap is published:
- brew tap nats-io/nats-tools
- brew install nats-io/nats-tools/nsc
To uninstall:
- brew uninstall nats-io/nats-tools/nsc
- brew untap nats-io/nats-tools
Note that the repo hosting the taps is called homebrew-nats-tools, which the homebrew
tooling infers.

FIX #224 - homebrew tap generation via goreleaser

---

cmd/init.go

There are a few cmd Printf messages that look wrong...
```sh
nsc init -d /nsc
[ OK ] created operator gracious_stallman
[ OK ] created account gracious_stallman
[ OK ] created user "gracious_stallman"
[ OK ] project jwt files created in "/nsc"
[ OK ] user creds file stored in "/nsc/nkeys/creds/gracious_stallman/gracious_stallman/gracious_stallman.creds"
> to run a local server using this configuration, enter:
> cmd.Printf("> nsc generate config --mem-resolver --config-file <path/server.conf>
> cmd.Printf("start a nats-server using the generated config:
> cmd.Printf("> nats-server -c <path/server.conf>
all jobs succeeded
```
With the changes it looks like this now:
```sh
[ OK ] created operator heuristic_gates
[ OK ] created account heuristic_gates
[ OK ] created user "heuristic_gates"
[ …
```

Update NSC init message

---

README.md
install.py
install.sh

This is not quite POSIX shell, we do ask for `local` to be available, and a few basic commands.  It's about as portable as I can make it without twisting into deep knots which risk adding bugs.
External commands required beyond POSIX: curl unzip mktemp
Document the usage of this script.
Adjust the Python to also use ~/.bashrc not ~/.bash_profile because the profile won't be run in all situations while the rc file should be used whenever the user has an interactive bash shell.
Usage for the shell differs slightly from the Python; it has a `-h` help option:
% ./install.sh -h
Usage: install [-t <tag>] [-d <dir>] [-s <dir>]
-d dir     directory to download into [default: ~/.nsccli/bin]
-s dir     directory in which to place a symlink to the binary
[default: ~/bin] [use '-' to forcibly not …

Add a portable shell install script

---

cmd/describe.go
cmd/describeaccount.go
cmd/describeaccount_test.go
cmd/describeoperator.go
cmd/describeoperator_test.go
cmd/describeuser.go
cmd/describeuser_test.go
cmd/jsonpath.go
cmd/jsonpath_test.go
cmd/util_test.go

added `--field` option, which loads the body of the jwt as JSON and then performs a JSON path evaluation.
The argument should be the field path separated by dots: `a.b.c[12].d` Note that you can reference indexed values etc.

added jsonpath support to describe to support tools

---

cmd/addaccount_test.go
cmd/adduser.go
cmd/adduser_test.go
cmd/signerparams.go
cmd/util_test.go

creating a user or a managed account by specifying a public key that is stored in the keystore will fail generation of creds or creation of the account.

FIX #246 account/user with stored keys

---

cmd/defaults.go
cmd/env.go
cmd/options_test.go
cmd/root.go
cmd/store/keys.go
cmd/update.go
cmd/update_test.go
cmd/util_test.go
go.sum

FIX #240 - Added env variables to prevent the creation of `.gitignore`, performing self-update checks, or writing ~/.nsc.json.
- `$NSC_CWD_ONLY` - when set the context is based on the location of the CWD (operator/account).
- `$NSC_NO_SELF_UPDATE` - when set will skip any self-update checks
- `$NSC_NO_GIT_IGNORE` - when set will not write .gitignore files in the directory pointed to by - `$NKEYS_PATH`. If the nkeys are in a directory under revision control, it means that the secrets will be checked in. Exercise caution.

Add env variables to prevent certain user behaviours

---

cmd/addaccount_test.go
cmd/adduser_test.go
cmd/generatenkey.go
cmd/generatenkey_test.go

[fix] removed printing of seed key when storing a generated key. If the `--store` is not specified, the seed is printed.

seed prints when invoking `nsc generate nkey --xxxx --store

---

cmd/addoperator.go
cmd/addoperator_test.go
cmd/describer.go
cmd/init.go
cmd/init_test.go

Named SYS and sys
```
16:32:01  ~/repos/nsc  system_account *9 ?1  nsc init
? enter a configuration directory /Users/matthiashanel/nsc-test
? Select an operator Create Operator
? name your operator, account and user crazy_brahmagupta
[ OK ] created operator crazy_brahmagupta
[ OK ] created system_account: name:SYS id:ADLPUC4CEHJY2NLBV3ILXYGVHR42ZVHCX7Q2OEMCFCNYUNPFETXI2DAG
[ OK ] created system account user: name:sys id:UALD37FFZD7HNO7IKBW7KOGAW6BONFQAWKQI54UAHNUUBT4QNSGPUG4F
[ OK ] system account user creds file stored in `~/.nkeys/creds/crazy_brahmagupta/SYS/sys.creds`
[ OK ] created account crazy_brahmagupta
[ OK ] created user "crazy_brahmagupta"
[ OK ] project jwt files created in `~/nsc-test`
[ OK ] user creds file stored in …
```

Generate system account and user on init and add operator

---

cmd/defaults.go
cmd/env.go
cmd/pubtool.go
cmd/pull.go
cmd/push.go
cmd/replytool.go
cmd/reqtool.go
cmd/root.go
cmd/rtttool.go
cmd/subtool.go
cmd/tool.go
cmd/tools_test.go

When set the value will be used for nats connections.
When not set NSC_HOME/pkix/rootcas-nats.pem will be used, when present.
Else, default to system trust store.
Tried manually as setting env variables in tests and generating certs was harder than it should be.
Manually tried without env set, with rootcas-nats.pem absent/present/NSC_HOME changed.
Below is debug output from a manual test to assure that createDefaultToolOptions picks up the value set.
```
> nsc sub f
Error: x509: certificate signed by unknown authority
...
> export NSC_ROOTCAS_NATS=/Users/matthiashanel/test/rootCA.pem; nsc env
╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                           NSC …
```

Added env variable NATS_CA to provide root ca option to nats

---

cmd/init.go
cmd/store/store.go

Return struct instead of interface to avoid comparing interface with nil

---

cmd/common.go
cmd/importaccount.go
cmd/importaccount_test.go
cmd/importuser.go
cmd/importuser_test.go

If the account is self signed, resign with the operator.
manual test:
```text
> nsc delete account ACC
[ OK ] expired account "ACC"
[ OK ] deleted account
[ OK ] deleted account directory
> nsc import account --jwt import.jwt
[WARN] Validation resulted in: self-signed account JWTs shouldn't contain operator limits
[ OK ] Account ACC was successfully imported
1 job succeeded - 1 have warnings
> nsc import account --jwt import.jwt
[WARN] Validation resulted in: self-signed account JWTs shouldn't contain operator limits
[ERR ] Account already exists, overwrite with --overwrite
Error: 1 job failed - 0 job succeeded and 1 had warnings
Usage:
nsc import account <jwt file> [flags]
Examples:
nsc import account <jwt>
Flags:
-h, --help         help for …
```

[feat] Adding command to import account

---

cmd/addoperator.go
cmd/addoperator_test.go

Allow to overwrite an operator by same name and subject using --force

---

cmd/addaccount_test.go
cmd/addimport_test.go
cmd/addoperator_test.go
cmd/adduser_test.go
cmd/common.go
cmd/common_test.go
cmd/deleteexport_test.go
cmd/signerparams.go
cmd/store/store.go

Basically allow for multiple kinds to be specified.
Why this check exist is a mystery to me. Specifically because the caller also provides which keys are ok to use.
This makes it work such that in managed mode you can be set up with an operator signing key

[Fixed] managed stores with op signing key create signed accounts

---

cmd/addimport.go
cmd/addimport_test.go
cmd/generateactivation.go

[added] support for wildcard imports

---

cmd/reissueoperator.go
cmd/reissueoperator_test.go

Also resigns affected accounts
```
> nsc -h
nsc creates NATS operators, accounts, users, and manage their permissions.
Usage:
nsc [command]
Available Commands:
add         Add assets such as accounts, imports, users
delete      Delete imports and exports
describe    Describe assets such as operators, accounts, users, and jwt files
edit        Edit assets such as accounts, imports, and users
env         Prints and manage the nsc environment
export      Export assets such as nkeys
generate    Generate activations, creds, configs or nkeys
help        Help about any command
import      Import assets such as nkeys
init        Initialize an environment by creating an operator, account and user
keys        Manage keys for operators, accounts, and …
```

[added] command to re-issue operator identity key

---

cmd/adduser.go
cmd/common.go
cmd/common_test.go
cmd/editaccount.go
cmd/editaccount_test.go

change unit converstion from 1000 to 1024 and removed printf

Minor fixes to make js work when only js params are provided

---

cmd/wellknownoperator.go

This will disable this version of nsc in ngs

Temporarily changed operator url back to v2

---

cmd/addoperator_test.go
cmd/generateactivation_test.go
cmd/init_test.go
cmd/migrate_test.go
cmd/pull.go
cmd/pull_test.go
cmd/push_test.go
cmd/store/store.go
cmd/util_test.go
cmd/wellknownoperator.go

made operator pulls check v2 before v1, this is just a temporary solution, as the correct thing is to change the account server to handle a query string parameter to determine if the client is looking for a v2 JWT.
FIX #388

`nsc pull -A` overwrites v2 operator with a v1

---

cmd/root.go

expanded on the help message provided for upgrading to v2. In the case of NGS it can be simpler

---

cmd/push.go
cmd/store/keys_test.go

Some of these cases on nsc have no integration tests (they require an account server)

The keystore API returns nil for a keypair and nil error if the key is not found

---

install.sh

The `uname -p` command can return `unknown`, even while `arch` returns a real value.  Even though uname is more widely guaranteed to be present.  So, handle "unknown" as a special case and try arch(1).  If calling arch fails then we'll abort and we're no worse off than we were with an "unknown" value.
Make sure that errors inside command substitution sub-shells propagate properly out, by splitting a printf invocation to use an intermediate variable setting first; this way, printf(1) won't swallow the $? and mask it, and we can force an exit if the sub-shell failed.
This repairs an installability regression introduced with the switch to multi-arch support (for handling arm64); prior to that, we assumed amd64 always.

Installer: Unbreak Alpine in Docker

---

cmd/addexport.go
cmd/addexport_test.go
cmd/addimport.go

[FIX] removed misleading flag help for service as only supported on public imports
[FEAT] Added support for `--account-token-position`
[FEAT] Added support for `--advertise` (hidden) for public exports.
The `--account-token-position` allows public exports from an account to be constrained to
a subject that is clamped to the account. The NATS server will ensure that only an
importing account sporting a matching public key in the specified wildcard token can
access the service/stream. This removes the burden of generating a token for subjects
that follow such a pattern on system-wide services

Account token position

---

cmd/generatediagram.go

[fixed] export/import type mismatch in diagram generation

---

cmd/defaults.go
cmd/env.go
cmd/root.go
cmd/tool.go

This allows to specify key and cert for nats connection connecting to a
server requiring client certs.
Fixes #408

[added] support for evn vars  NATS_KEY & NATS_CERT for verify=true

---

cmd/edituser.go

The flag "--conn-type" defines the allowed connections. If you define --conn-type MQTT, the user will **exclusively** have access via MQTT.
This bahaviour is not properly stated / documented. Therefore I suggest to adjust the flag description.
The feature description and behaviour was introduced here: https://github.com/nats-io/jwt/pull/97

DOCS: conn-type flag description

---

cmd/adduser.go
cmd/adduser_test.go

Because the user aleady had an issuer, you could never re-sign with a
different key.

fixed scoped signing key re-signing issue

---

cmd/generatediagram.go

`*` is some sort of special relationship notation for plantuml
without change 
with change

added code to keep plantuml from rendering * as O

---

cmd/editoperator.go
cmd/editoperator_test.go
cmd/generateprofile.go

[FIX] added `--rm-account-jwt-server-url` to remove the account server url from the operator JWT.
FIX #446

[FIX] added `--rm-account-jwt-server-url`

---

cmd/addoperator.go

I think this should address https://github.com/nats-io/nsc/issues/429
Instead of throwing away the error from fetching the path as a url, hold on to it and if fetching as path also fails, return the first error.

show better error when adding operator w/ bad url

---

cmd/store/keys.go
cmd/store/store.go

This is useful for other libraries depending on `nsc/store` as it allows to check for error types, rather than match them against strings (if conditionals are required).
Part of improving user experience in NGS which could print nicer error messages in some scenarios.

Wrap store module errors

---

cmd/generateprofile.go
cmd/load.go

Given an URL it will bootstrap the store and keys folder structure and create a default user for an account plus a configured nats context.
Well known operators:
```sh
nsc load --profile "nsc://synadia?secret=SAABONGWSU7EWYZV3VAFFSP45P7NG3G67OLVRMA56UGZ2B3IYOGXAIFHLQ&user=bar"
```
Custom operators:
```sh
nsc load --url "http://localhost:9090/jwt/v1/operator" \
--seed SAABONGWSU7EWYZV3VAFFSP45P7NG3G67OLVRMA56UGZ2B3IYOGXAIFHLQ \
--user hello
```
Example usage:
```sh
$ nsc load --user hello2 --url "http://localhost:9090/jwt/v1/operator" --seed SAABONGWSU7EWYZV3VAFFSP45P7NG3G67OLVRMA56UGZ2B3IYOGXAIFHLQ
[ OK ] push jwt to account server
[ OK ] pull jwt from account server
[ OK ] generated and stored user key "UAIXTULQFMPW75TCE6TV7WYFLWQPXURNSNXRTQCJROSBPTQNTRV4DUQ5"
[ OK ] generated and stored …
```

Add nsc load cmd

---

.github/workflows/release.yaml
.goreleaser.yml

In debugging missing architectures from the generated brew data, it eventually was "goreleaser bug, fixed in newer patchlevel release".
We had one bug in that the archive names for 32-bit ARM would have a vN suffix but the specification for brew did not include that.  Fixed, and include a reference to the default and just leave all the architecture finangling in-place in both.
nsc is under the Apache-2.0 license (SPDX identifier), so tell Brew that.

Lock goreleaser version, adjust name templates; license

---

.github/workflows/release.yaml
.goreleaser.yml

Cross-repo action access is an "interesting" security proposition right now.  Instead, skip the upload but register the formula as a build artifact, where it can be found to make a manual fix to the homebrew tap repo.
It's the least-bad solution.
WARNING 1: this is an _untested_ fix.  It looks sane to me.
WARNING 2: I'm about to head out the door for a long weekend vacation.  Merge or not as you see fit, to balance risk of "needing a release" vs "debugging if things go wrong", but since things are broken in GHActions right now without this, I don't think this will make things _worse_.
:speak_no_evil: famous last words.

Don't ask GitHub Actions to upload brew formula

---

cmd/pubtool.go

Added a missing validation check for the user context params. 
```
go run main.go pub -a A foo bar
Error: a user is required
Usage:
nsc pub [flags]
```
FIXES #491

[FIX] added a validation check on the user context params

---

cmd/pubtool.go
cmd/replytool.go
cmd/subtool.go
cmd/tools_test.go

Currently, permission violations are ignored.
The `pub` command returns a success exit code, even though there is a permission violation.
```
$ nsc tool pub --nats nats://foo:foo@localhost:4222 bad hi
Published [bad] : "hi"
nats: Permissions Violation for Publish to "bad" on connection [11]
$ echo $?
0
```
The `sub` command waits on a subscription, even though there is a permission violation.
```
$ nsc tool sub --nats nats://foo:foo@localhost:4222 bad
Listening on [bad]
nats: Permissions Violation for Subscription to "bad" on connection [4]
```
The `reply` command waits on a subscription, even though there is a permission violation.
```
$ nsc tool reply --nats nats://foo:foo@localhost:4222 bad hi
listening on [bad]
nats: Permissions Violation for Subscription to "bad" on connection [4] …
```

Report permission errors while using tools

---

cmd/edituser.go
cmd/edituser_test.go

This changes the wording on a log message when the `--bearer` flag is set.
```
$ nsc edit user --deny-sub foo
[ OK ] added deny sub "foo"
[ OK ] generated user creds file `~/.local/share/nats/nsc/keys/creds/dreamy_driscoll/myacc/myusr.creds`
[ OK ] edited user "myusr"
$ nsc edit user --deny-sub foo --bearer=false
[ OK ] ensured bearer is false
[ OK ] added deny sub "foo"
[ OK ] generated user creds file `~/.local/share/nats/nsc/keys/creds/dreamy_driscoll/myacc/myusr.creds`
[ OK ] edited user "myusr"
$ nsc edit user --deny-sub foo --bearer=true
[ OK ] ensured bearer is true
[ OK ] added deny sub "foo"
[ OK ] generated user creds file `~/.local/share/nats/nsc/keys/creds/dreamy_driscoll/myacc/myusr.creds`
[ OK ] edited user "myusr"
```
Fixes https://github.com/nats-io/nsc/issues/405

Change the wording on the bearer flag

---

cmd/defaults.go
cmd/defaults_test.go

With `--data-dir`, Current Store Dir taken from config file.
```
$ nsc --config-dir "~/.config/nats/nsc" --data-dir "/tmp/data-dir" --keystore-dir "/tmp/keystore-dir" env
+----------------------------------------------------------------------------------------------------------+
|                                             NSC Environment                                              |
+--------------------+-----+-------------------------------------------------------------------------------+
| Setting            | Set | Effective Value                                                               |
+--------------------+-----+-------------------------------------------------------------------------------+
| $NSC_CWD_ONLY      | No  | If set, default operator/account from cwd only …
```

Set StoreRoot as dataDir if set

---

cmd/timeparams.go
cmd/timeparams_test.go

[FIX] when parsing start/expiry expressions the value must be integral

---

cmd/signingkeyseditor.go

The command `nsc edit operator --sk generate` currently save 2 nkeys in the store:
- A first one when doing the Validate,
- a second one when doing the Run.
This prevent the validate to generate a nkey and save it.

Fix creation of extra nkey with --sk generate

---

cmd/root.go

This PR changes the default output of `nsc` from printing the version to showing the help.

Set Default output to help

---

cmd/select.go
cmd/select_test.go

This PR adds the `select` verb to the `nsc` command. The goal was to more explicitly expose the functionality to switch operators and accounts and to make it as easy as possible.

Add `select` Command

---

cmd/adduser.go

When an operator is configured to require a signing key (`StrictSigningKeyUsage`) but there are no signing keys configure on an account, using interactive mode to create a user results in a null pointer error: the resolved signing key slice is empty and interactive mode attempts to auto select index 0 which doesn't exist.
This PR will return a descriptive error to the user indicating that signing keys are required but no signing keys are available for use.

Fix: null pointer error in add user interactive mode

---

cmd/describejwt.go

The current example is stated as:
```
$ nsc describe jwt
Error: file is required
Usage:
nsc describe jwt [flags]
Examples:
nsc describe -f pathorurl
```
When the example should be `nsc describe jwt -f pathorurl` as the other command is non-existing

chore: fix example for `describe jwt`

---

README.md

The docker example references chmod but it should be chown.

Correct readme chmod to chown reference

---

cmd/exportkeys.go
cmd/exportkeys_test.go
cmd/keycollector.go

added `--include-jwtws` option to make it easy to export not only the keys, but also the configurations in the current operator tree. Paired with `nsc fix` you can recreate/mode an nsc environment.

[FEAT] export an entire environment (jwts and keys)

---

cmd/env_test.go
cmd/root.go
cmd/util_test.go

added `--all-dirs` option to store config, data, keys under the same directory - this is useful for generating test configurations

[FEAT] added single flag to set all the data/keys/config to one containing dir

---

cmd/addimport_test.go
cmd/adduser_test.go
cmd/importcollector.go

[FIX] imports with the same name from different accounts get confused when using interactive mode - the cli ui is comparing strings and returns the last one match rather than the one at the current selection. The fix simply adds the src account name which disambiguates the entry

[FIX] interactive imports when two accounts export same subject confuse the source account selection

---

README.md

The docker image given in the example on how to launch nats-box was pointing to the synadia one that haven't been updated since April 2021. Updated the example to `natsio/nats-box`

correct nats-box docker image in readme

---

cmd/addaccount.go
cmd/addaccount_test.go
cmd/addoperator.go
cmd/addoperator_test.go
cmd/adduser.go
cmd/adduser_test.go

[FIX] entity names using a path separator are parsed as a path, which then writes them to the wrong location in the store - this fix generates an error if for such names
FIXES #398

prevent entity names with path separators

---

cmd/exportkeys.go
cmd/generateprofile.go
cmd/generateprofile_test.go

[FIX] generate profile now sets the current context for the specified nsc:// url
[FEAT] added 'seeds', 'keys', 'names' to the options - this adds the specified values to all the entities affected by the specified nsc url
FIX #508

Set initial context of generate profile to the provided nsc url

---

cmd/describe.go
cmd/describeaccount_test.go

[FIX] default go marshaller encodes HTML entities - changed so that when describe is outputting JSON to the console, to not do so

---

.github/workflows/pushes.yaml
cmd/importaccount_test.go
cmd/importuser_test.go
cmd/pubkeyparams.go
cmd/revoke_listusers_test.go
cmd/revokeuser_test.go

* Add a CI push test to fail the build if the binary pulls in jwt library v1
+ this should be extensible enough as a pattern to let us handle any other deny-list libraries we want to keep out
* Fix `cmd/pubkeyparams.go` which accidentally pulled in jwtv1 not jwtv2, to get the constant `jwt.All` (`"*"`)
* Change all test files which didn't explicitly pull in jwt/v1 _as_ `jwtv1` to bring in jwt/v2 instead
+ If the test says jwtv1 explicitly, it's assumed to be deliberate
As long as any tests pull in JWTv1, the go.mod file will continue to reference v1, so we can't just audit the module file for sanity; we instead build the binary and look at what it's actually using.

Get jwt library v1 out of the nsc binary

---

.github/workflows/release.yaml
.goreleaser.yml
release/sign-cosign

Most critically: cosign now requires --yes to confirm that it's okay for signatures to be uploaded, even when ... not using OIDC flows.  Sigh.
While doing releng treading-water tasks:
* all future tags are v-preficed if they're for release
* bump goreleaser to current
+ adjust goreleaser invocation/config for deprecation warnings
Intent to backport: this needs to be applied to rel-2.7 too

unbreak release tooling, versions bump

---

cmd/generatecontext.go

For `generate context` command example, flag `--name` should be replaced with `--context`.

Fix example for 'generete context' command

---

cmd/importaccount.go
cmd/store/store.go
cmd/store/store_test.go

[FIX] added checks the store API for situations where the returned store by a context is nil; this prevents panics when trying to resolve entities that cannot be referenced due to the lack of context. 
FIXES #578

[FIX] panics related to uninitialized environment

---

cmd/editaccount.go
cmd/editaccount_test.go
cmd/editoperator.go
cmd/editoperator_test.go

[FIX] clarified check added to edits of the system account which prevented editing due to JetStream default values in the flag - added a flag that sets the values for the jetstream setting (--js-disable) which sets the values to 0
Fixes #569

Clarify system account edits which requires JetStream limits to be set to 0

---

cmd/env.go
cmd/env_test.go
home/home.go

[TEST] changed tests to deduce the effect of the flag without relying on the env.
[FIX] deprecated NKEYS_PATH and NSC_HOME - installations should use XDG_DATA_HOME and XDG_CONFIG_HOME instead. Added these variables to the `nsc env` report
Fixes #563

Fixed env tests checking for --all-dirs flag

---

cmd/editoperator_test.go
cmd/store/istore.go
cmd/timeparams.go

[FIX] the --expiry and --start flags had a default value of 0, which meant no expiration - this would cause any previous values to be removed when setting other values on the JWT

expiry and start reset if not specified

---

cmd/expirations.go
cmd/expirations_test.go

[FEAT] added an expirations command, which traverses the current operator checking for JWTs and creds that expire within a specified amount of time (by default, a month). The command can generate a report in JSON format that could be used by other tooling.

[FEAT] expirations command

---

cmd/generateserverconfig.go

[FIX] generate command has a generic processing engine but when generating anything but nkey configurations, it shouldn't look at the users as this could significantly degrate generation performance when that data is not needed.

[FIX] generate --mem-resolver performance in setups that have huge number of users

---

cmd/editscopedsk.go
cmd/editscopedsk_test.go
cmd/signingkeyseditor.go

[FEAT] changed `edit signing-key` to allow `--sk generate`, or infer the sk if the value for the role is given or just the role is given
FIX #633

Enhancements to edit signing-key

---

install.py

Added armv7l to list of recognized CPU types. Now retrieves the armv7 ZIP artifact.

install script update to recognize armv7l CPU, Raspberry Pi 3B+

---

cmd/deleteuser.go
cmd/deleteuser_test.go

[FIX] relaxed requirement for the operator key when deleting an user if --revoke was not specified.

---

cmd/describer.go
cmd/editaccount.go
cmd/editaccount_test.go
cmd/editoperator.go
cmd/editoperator_test.go
cmd/edituser.go
cmd/edituser_test.go
cmd/genericclaimparams.go
cmd/push_test.go
go.mod
go.sum

[CHANGE] Tags (--tag and --rm-tag) are now case-sensitive
[FIX] describe accounts was not printing tags associated with the account
Fixes https://github.com/nats-io/nats-server/issues/5681

Tags are now case-sensitive, describe account lists tags associated with the account

---

cmd/addexport.go
cmd/editexport.go

Improve error reporting by replacing direct error returns with detailed validation result handling. This ensures better clarity and consistency in identifying and addressing validation errors in both `addexport` and `editexport` commands.

Refactor export validation error handling.

---

README.md

The badge was generated with:
https://pkg.go.dev/badge/

Update README.md: fix broken go reference link

---

cmd/editaccount.go
cmd/editaccount_test.go
cmd/validate.go
cmd/validate_test.go

- [FIX] added check for --js-enable=tier on system account
- [FIX] added bypass to allow --js-disable to work on system account in cases where it was enabled by specifying --js-enable=tier 
- [FIX] enhanced validation to check for system accounts with enabled jetstream
Fixes #684

various fixes regarding enable/disable/validation of Jetstream in the system account

---

cmd/load.go
go.mod

This commit cleans up the code by removing the unused `jsm.go` module and the `configureNATSCLI` function, which relied on it. The change reduces unnecessary dependencies and simplifies the `LoadParams` logic, improving maintainability.

Remove unused `jsm.go` dependency and `configureNATSCLI` logic.

---

README.md

also, drop outdated info about pre-go modules setup

Update README.md: add binaries.nats.dev

---

go.mod
go.sum

NATS Server releases v2.11.1 and v2.10.27 include a fix
for a security vulnerability (CVE):
https://advisories.nats.io/CVE/secnote-2025-01.txt
This PR updates to a patched version that is not vulnerable.
If applicable to this repo, we should also cut a release after merging.
This is a batch change created with https://github.com/lindell/multi-gitter
```
go get github.com/nats-io/nats-server/v2@patch
go get toolchain@none
go mod tidy
```
All PRs in this batch:
https://github.com/search?q=label%3Aabozhenko_multigitter_bump_nats_server_cve_2025_04+state%3Aopen&type=pullrequests

chore: update nats-server go module

---

cmd/pull.go
cmd/push.go
cmd/tool.go

Add TLS support to push, pull, and tool commands
- Introduced `--tls-first`, `--ca-cert`, `--client-cert`, and `--client-key` flags
- Updated the `push`, `pull`, and `tool` commands to support TLS configuration options.
Fixes #737

feat: tls first for push/pull and tool commands

---

cmd/describer.go

Some unlimited settings in the server are expressed as `0`.  - changed these to reflect that the unset values (0) is actually `Unlimited`
fixes #746

Handle unlimited limits in resource descriptions gracefully
