- .goreleaser.yml
- cmd/update.go
- main.go
changed formatting of the build artifact so the updater can see it added code to do the initial check of the updater
> self-updater

- cmd/editaccount.go
- cmd/editaccount_test.go
- cmd/numberparams.go
- cmd/numberparams_test.go
Signed-off-by: Derek Collison <derek@nats.io>
> Allow account edit to change Limits.Conn

- cmd/addaccount.go
- cmd/addcluster.go
- cmd/addexport.go
- cmd/addimport.go
- cmd/addserver.go
- cmd/adduser.go
- cmd/common.go
- cmd/deleteexport.go
- cmd/deleteimport.go
- cmd/describeaccount.go
- cmd/describecluster.go
- cmd/describejwt.go
- cmd/describeoperator.go
- cmd/describeserver.go
- cmd/describeuser.go
- cmd/editaccount.go
- cmd/editcluster.go
- cmd/editserver.go
- cmd/edituser.go
- cmd/env.go
- cmd/generateactivation.go
- cmd/generateconfig.go
- cmd/generateconfig_test.go
- cmd/generateoperatorconfig.go
- cmd/init.go
- cmd/list.go
- cmd/update.go
wrapped MaxNArgs from cobra to enable tests to be debugged
> [FIX-40] fixed selection of user on interactive mode

- cmd/describer.go
- cmd/editaccount.go
- cmd/editaccount_test.go
Fixed Operator describer to display standard JWT claims, including issuer.
> Added flag to edit leaf node connections

- cli/prompts.go
- cli/sui.go
- cli/testprompts.go
- cmd/addaccount_test.go
- cmd/addoperator.go
- cmd/adduser_test.go
- cmd/common.go
- cmd/editoperator_test.go
- cmd/signerparams.go
- cmd/signingkeyseditor.go
- cmd/store/keys.go
- cmd/timeparams.go
Fixed issue related external nkey signer for adding an operator
> Relaxed expiration dates

- cmd/rtttool.go
Added an rtt tool and updated help on req tool
> Added rtt tool

- install.py
FIX #153 - linux can be reported as `linux2` or `linux3`, added fix to simplify reported os name to `linux`.
FIX #154 - windows nsc is installed as `nsc` instead of `nsc.exe`. Also added snippet to aid the user in adding the installation directory to the windows path.
> installer fixes

- cli/testprompts.go
- cmd/common.go
- cmd/common_test.go
- cmd/contextconfig.go
- cmd/deploy.go
- cmd/env.go
- cmd/init.go
- cmd/init_test.go
- cmd/migrate_test.go
- cmd/push.go
- cmd/util_test.go
- cmd/wellknownoperator.go
- cmd/wellknownoperator_test.go
Support for local, remote, well known operator, with custom location for the project files.
> Init cmd changes

- cmd/keys_test.go
- cmd/store/keys.go
- cmd/store/keys_test.go
When using ngs and nsc, the keyring could get two different layouts
> added check for a mixed keyring

- cmd/init.go
- cmd/wellknownoperator.go
- cmd/wellknownoperator_test.go
Define as env variable "NSC_<name>_OPERATOR" with an URL value.
> Added ability to read named operators from the environment.

- cmd/export.go
- cmd/exportkeys.go
- cmd/exportkeys_test.go
- cmd/importkeys.go
- cmd/importkeys_test.go
- cmd/keycollector.go
- cmd/listkeys.go
- cmd/store/keys.go
- cmd/store/keys_test.go
- cmd/store/status.go
import and export keys. Export includes an option to remove exported keys from the keyring.
> Import export keys

- cmd/pull.go
- cmd/pull_test.go
Added flag --overwrite-newer to prevent clobbers when the local jwt is modified out band locally and the remote server has an older copy.
If the issue time is newer locally, the user will be prompted to use the
flag to perform the pull.
> Prevent pull from clobbering newer configurations on disk.

- cmd/init.go
- cmd/store/status.go
server messages are interspersed with command status messages. Reformatted to provide better legibility.
> Reformatted messages to provide better legibility to messages generated by the server

- cmd/addaccount.go
- cmd/addaccount_test.go
- cmd/adduser.go
- cmd/adduser_test.go
- cmd/init.go
- cmd/init_test.go
- cmd/names_generator.go
- cmd/names_generator_test.go
- cmd/pubtool.go
- cmd/replytool.go
- cmd/reqtool.go
- cmd/rtttool.go
- cmd/subtool.go
- cmd/timeparams.go
- cmd/tool.go
Added random name option for init, add user and add account
Added --nats option for tools
Added expiration example
Added tests for same
> Sasbury misc

- cmd/init.go
- cmd/init_test.go
We allowed "" but not "*" in init :-( my bad, i fixed it.
> added support for * to init names

- cmd/init.go
- cmd/init_test.go
> added check to validate that the account name doesn't exist on init

- cmd/editoperator.go
- cmd/edituser.go
- cmd/genericclaimparams.go
- updated editoperator/user to use new output mechanism
- fixed start/expiry params to only show messages when actually changing them.
> message fixes

- cmd/describeaccount.go
- cmd/describeoperator.go
- cmd/describeuser.go
- added status to process of describing (when directing to a file)
- added decorations to the jwts when --raw and directing to a file
> decorating raw jwts (describe cmd)

- cmd/deleteuser.go
- cmd/deleteuser_test.go
- cmd/store/store.go
> implemented delete user

- Makefile
- cmd/addaccount_test.go
- cmd/addoperator_test.go
- cmd/common_test.go
- cmd/deleteaccount_test.go
- cmd/deleteuser_test.go
- cmd/describeaccount_test.go
- cmd/describejwt_test.go
- cmd/describeoperator_test.go
- cmd/describeuser_test.go
- cmd/editexport_test.go
- cmd/editoperator_test.go
- cmd/exportkeys_test.go
- cmd/friendlynamecollector_test.go
- cmd/generatenkey_test.go
- cmd/init_test.go
- cmd/keys_test.go
- cmd/memresolverconfigbuilder_test.go
- cmd/migrate_test.go
- cmd/rename_test.go
- cmd/util_test.go
- cmd/validate_test.go
Static check fixes for the tests. Code base in a different PR as some of the warnings are due to APIs made to support ngs.
> linted the tests

- .travis.yml
- Added windows build on travis
- Fixed missing goveralls
> adding windows to travis - fixing goveralls

- cmd/deleteuser.go
- cmd/deleteuser_test.go
> expose account flag to delete user cmd

- cmd/describeuser_test.go
- cmd/edituser.go
- cmd/edituser_test.go
- cmd/generateprofile_test.go
```
19:45:30  ~/repos/nsc  master *9 !69 ?30  nsc edit user -n foo --time "16:04:05-17:04:09" --time "18:04:05-19:04:09"
[ OK ] added time range 16:04:05-17:04:09
[ OK ] added time range 18:04:05-19:04:09
[ OK ] generated user creds file `~/.nkeys/creds/test3/SYS/foo.creds`
[ OK ] edited user "foo"
19:45:55  ~/repos/nsc  master *9 !69 ?30  nsc describe user foo
╭─────────────────────────────────────────────────────────────────────────────────╮
│                                      User                                       │
├──────────────────────┬──────────────────────────────────────────────────────────┤
│ Name                 │ foo                                                      │
│ User ID              │ …
```
> Added support for logon times

- cmd/revoke_clearactivation.go
- cmd/revoke_listactivation.go
- cmd/revoke_listusers.go
- cmd/revokeactivation.go
- cmd/revokeclearuser.go
- cmd/revokeclearuser_test.go
- cmd/revokeuser.go
- cmd/revokeuser_test.go
> [Adding] ability to revoke user by nkey only

- cmd/addaccount_test.go
- cmd/adduser_test.go
- cmd/signerparams.go
> added auto-selection of signing key on non-interactive mode

- cmd/addimport.go
- cmd/generateactivation.go
fixed message displayed when saving an activation token to disk.
> fixed bogus message

- cmd/describer.go
- cmd/env.go
- cmd/list.go
- cmd/listkeys.go
- cmd/revoke_listactivation.go
- cmd/revoke_listusers.go
- cmd/util_test.go
- cmd/validate.go
changed tables to ASCII this allows for simpler and more consistent presentation, also matches the output from jetstream tools.
> [feat] use ascii tables

- cmd/store/status.go
Fixed check of nil on interface return value which bypasses the nil check to fail further down.
> fixed status adding nil values that had interface.

- cmd/importaccount.go
> Fixed issue where an error was raised when no key was present

- cmd/describejwt.go
- cmd/describejwt_test.go
> [fix] added support for JSON/Path/Raw describe options

- cmd/adduser.go
- cmd/adduser_test.go
- cmd/edituser.go
- cmd/edituser_test.go
> [feat] select from multiple keys when signing user

- cmd/addoperator.go
- cmd/addoperator_test.go
- cmd/common_test.go
- cmd/importaccount.go
- cmd/importaccount_test.go
- cmd/importuser.go
- cmd/importuser_test.go
- cmd/root.go
- go.mod
added check to protect against importing account/operator/user jwtv2
added check to protect against using a jwtv2 store
> [added] check to protect against jwtv2 usage and provide instructions

- cmd/root.go
- go.mod
- go.sum
- vendor/github.com/nats-io/jwt/.gitignore
- vendor/github.com/nats-io/jwt/.travis.yml
- vendor/github.com/nats-io/jwt/Makefile
- vendor/github.com/nats-io/jwt/README.md
- vendor/github.com/nats-io/jwt/account_claims.go
- vendor/github.com/nats-io/jwt/claims.go
- vendor/github.com/nats-io/jwt/cluster_claims.go
- vendor/github.com/nats-io/jwt/creds_utils.go
- vendor/github.com/nats-io/jwt/exports.go
- vendor/github.com/nats-io/jwt/go.mod
- vendor/github.com/nats-io/jwt/go.sum
- vendor/github.com/nats-io/jwt/header.go
- vendor/github.com/nats-io/jwt/imports.go
- vendor/github.com/nats-io/jwt/operator_claims.go
- vendor/github.com/nats-io/jwt/revocation_list.go
- vendor/github.com/nats-io/jwt/server_claims.go
- vendor/github.com/nats-io/jwt/types.go
- vendor/github.com/nats-io/jwt/validation.go
- vendor/modules.txt
> Updated jwt library

- cmd/addaccount.go
- cmd/addaccount_test.go
- cmd/adduser.go
- cmd/describer.go
- cmd/editaccount.go
- cmd/editaccount_test.go
- cmd/editexport.go
- cmd/editexport_test.go
- cmd/editoperator.go
- cmd/editoperator_test.go
- cmd/edituser.go
- cmd/edituser_test.go
- cmd/importcollector.go
- cmd/signerparams.go
- go.mod
- go.sum
- vendor/github.com/nats-io/jwt/v2/account_claims.go
- vendor/github.com/nats-io/jwt/v2/exports.go
- vendor/github.com/nats-io/jwt/v2/imports.go
- vendor/github.com/nats-io/jwt/v2/types.go
- vendor/modules.txt
each commit is a separate change. (except first one, that just pulls in the latest jwtv2 changes)
> V2 fields 2

- cmd/upgradejwt.go
> Change upgrade prompts to be lower case

- cmd/generatediagram.go
> [Added] ability to generate component or object diagrams of the store

- cmd/root.go
> allow nsc update to work when encountering jwt v1 operator

- cmd/addexport.go
- cmd/addexport_test.go
- cmd/addimport.go
- cmd/addimport_test.go
- cmd/editexport.go
- cmd/editexport_test.go
- cmd/root.go
> [Added] options to enable headers for latency tracking and sharing

- cmd/addexport.go
- cmd/addexport_test.go
- cmd/common.go
- cmd/editexport.go
- cmd/editexport_test.go
> [Added] support for service export response threshold

- cmd/generatediagram.go
and minor bug fixes and option to disable notesn
> Improve component diagram: better display of imports without exports

- cmd/importaccount.go
- cmd/importaccount_test.go
> [added] option to import account signed by different operator

- cmd/addoperator.go
- cmd/addoperator_test.go
- cmd/reissueoperator.go
- cmd/reissueoperator_test.go
added operator name option to reissue
> [added] force import of operator with different subject

- cmd/describejwt.go
- cmd/generatediagram.go
> [chore] change help text and revisit diagrams

- cmd/addoperator.go
- cmd/wellknownoperator.go
- cmd/wellknownoperator_test.go
> [changed] well known synadia operator url to use v2

- cmd/edituser.go
- cmd/edituser_test.go
> [added] ability to set locale to use for times

- cmd/addimport.go
- cmd/common.go
- cmd/editaccount.go
- cmd/revokeactivation.go
- cmd/revokeactivation_test.go
- cmd/revokeuser.go
- cmd/revokeuser_test.go
[chore] remove mentioning of import prefix
[Added] support for rfc3339 formatted time when revoking
Fix js error when modifying the system account
> Minor fixes

- cmd/addimport.go
- cmd/describer.go
Also straighten out table header
> Avoid always setting local subject and adding a prefix in interactive

- cmd/dataparams_test.go
- cmd/describer.go
- cmd/edituser.go
- cmd/edituser_test.go
- [feat] added --data and --subs flags to set the data and sub limits on the user
- [fix] fixed an issue where payload was not honoring entries like "5M" or "5K"
- [chore] added test to the dataparams
- [chore] fixed some linter warnings
FIX #362
> user limits

- cmd/root.go
- cmd/upgradejwt.go
> Changed version numbers and descriptions for jwt update scenarios

- cmd/adduser.go
- cmd/adduser_test.go
- vendor/modules.txt
> [fixed] unused source-network option during add user

- cmd/push.go
- cmd/push_test.go
most of the change is moving code into separate functions.
> [added] option to remove account and diff which accounts exist where

- cmd/generatediagram.go
> [fixed] special char issues in diagram generation

- cmd/addimport_test.go
- cmd/pubkeyparams.go
> [added] support for account key lookup by name in pubkeyparams

- cmd/pubkeyparams.go
- cmd/root.go
- cmd/upgradejwt_test.go
> added ignore for message that is shown as is to user

- .goreleaser.yml
> added darwin arm64 (m1) support

- cmd/addimport.go
- cmd/describer.go
- cmd/init.go
```
> nsc add operator -n OP --sys
[ OK ] generated and stored operator key "OBUZWSVUKIL2OO2XOMPB6UQW6MQXRHHAM6OYATGK2S7XCFR3DD7755TA"
[ OK ] added operator "OP"
[ OK ] When running your own nats-server, make sure they run at least version 2.2.0
[ OK ] created system_account: name:SYS id:ADU44BYVVHD7ZU5AW7PHJ3ZPOC2ZNGOM3HTLKRHQQZLJ7MOXB7V3M6Y2
[ OK ] created system account user: name:sys id:UBZXNHKJAJQ4ANORQPM72GWTVZN3WI7OXZBSI3564BRJZD3SI7XJIKGT
[ OK ] system account user creds file stored in `~/test/test-nsc/keys/creds/OP/SYS/sys.creds`
> nsc add account -n TEST
[ OK ] generated and stored account key "ACKZBVK35JV4HNXS52IJPWJYW6T3ZNTWUJPAVGGA2OO7S4WRODIX6QAI"
[ OK ] added account "TEST"
> nsc add import -i
? select account TEST
? pick from …
```
> [added] default exports to default system account and improved importing

- cmd/editoperator.go
> [fixed] help text to inlcude nats url for account-jwt-server-url

- cmd/addmapping.go
- cmd/deletemapping.go
- cmd/deletemapping_test.go
- cmd/describer.go
> [added] support for mappings

- cmd/describer.go
- cmd/editscopedsk.go
- cmd/editscopedsk_test.go
I believe user still have to improve the user
> [adding] support for scoped signing key

- cmd/adduser.go
- cmd/adduser_test.go
- cmd/describer.go
- cmd/describeuser.go
- cmd/editscopedsk.go
- cmd/editscopedsk_test.go
- cmd/edituser.go
- cmd/numberparams.go
- cmd/root.go
- cmd/signerparams.go
also changed describe for such user
Also moved tags (common field) around
```
nsc describe user --account SYS --name test
+---------------------------------------------------------------------------+
|                                   User                                    |
+----------------+----------------------------------------------------------+
| Name           | test                                                     |
| User ID        | UCH5FKMAM75PCERKSOPADAWV4HNNQ43UWSBO5Y3J43WS2RXCMKA6BWXH |
| Issuer ID      | AACYICOAQMQ72EHT35R7LV6VFWMIVWFKWFE5P2JJ2TT674EO7DJTUHMM |
| Issuer Account | ADECCNBUEBWZ727OMBFSN7OMK2FPYRM52TJS25TFQWYS76NPOJBN3KU4 |
| Issued         | 2021-07-14 19:33:14 UTC                                  |
| …
```
> [adding] support to create user from scoped signing key

- cmd/root.go
> [fixed] help text

- cmd/editscopedsk.go
- cmd/editscopedsk_test.go
- cmd/signerparams.go
> [adding] ability to edit scoped key by role name

- cmd/natsresolverconfigbuilder.go
> [added] timeout to generated nats-resolver config

- cmd/adduser.go
- cmd/signerparams_test.go
> [fixed] panic when signing with -K and a key that is not a signing key

- cmd/addexport.go
- cmd/addexport_test.go
> [fixed] missing error when response type was set for stream

- install.sh
Use a more portable and reliable invocation to get a better output of the current CPU architecture.
Fixes #443
> installer: use better CPU architecture query

- README.md
simple fix to report card badge urls are now https
> fixed report card badge

- README.md
> [FIX] updated script references to point to main

- .goreleaser.yml
- README.md
- Fix master -> main migration links
- sync goreleaser targets to include most natscli ones
> freebsd builds

- cmd/load.go
Fixes #474 
Signed-off-by: Waldemar Quevedo <wally@nats.io>
> Fix operator name used with load cmd

- cmd/adduser.go
> [FIX] message double 'pub' in message output, no message about --deny-sub

- dependencies.md
Signed-off-by: Waldemar Quevedo <wally@nats.io>
> Update dependencies file

- cmd/generateprofile.go
The `nsc generate profile` command should be able to emit JSON for any operator specified as a parameter; this is needed so that the natscli tool can use `nsc://` URLs in `$NATS_CONTEXT` definitions to reference users from any operator in the local store root.
Requiring that the correct operator already be the current operator defeats the whole point of being able to use `nsc://` URLs in the first place.
The `nsc generate profile` should not mutate the current profile.
This reworks the loading logic, without storing changes to the nsc.json settings, so that any known operator will work.
This does mean that various nsc settings to change where the store root is, or use CWD, will still impact upon the resolution of the URLs, but that's mostly reasonable: in the absence of overrides, nats …
> fix: nsc generate profile: use operator from URL

- cmd/editoperator_test.go
https://github.com/nats-io/nsc/pull/512
> [TEST] added test for PR #512

- cmd/editaccount.go
- cmd/editaccount_test.go
The new tiered limits feature added in #517 causes a validation failure
when a tier is set and a non-limits based flag is passed to update an
account.
This was discovered when trying to add a signing key to a fresh NGS
account.
> [fix] Tiered limits validation from blocking legitimate updates

- .github/workflows/release.yaml
List of things to confirm: https://github.com/nats-io/nsc/issues/530
Signed-off-by: Waldemar Quevedo <wally@nats.io>
> Prepare for release v2.7.6 

- cmd/addoperator.go
- cmd/adduser_test.go
- cmd/defaults.go
- cmd/list.go
- cmd/validate_test.go
this is experimental and requires manual testing, but seems to work correctly
FIX #513
> [FIX] use of env NSC_CWD_ONLY

- cmd/generatecontext.go
- cmd/generatecontext_test.go
- home/home.go
> [FEAT] generate a nats-cli context file for a specified user

- cmd/push.go
> [FIX] added optional timeout for nats-resolver based operations

- cmd/importaccount_test.go
- cmd/importuser.go
- cmd/importuser_test.go
[TEST] added test for importing accounts regardless of whether they are decorated or not
FIX #571
> [FIX] importing of user jwt files regardless of whether they are decorated or not

- cmd/importkeys.go
> [FIX] fixed import key `--recurse` flag name shown in the example - was listed as `--recursive`

- cmd/describeaccount.go
- cmd/describeoperator.go
- cmd/describeuser.go
see issue https://github.com/nats-io/nsc/issues/594
> fix: Generating of description for entities in combination of json and write to file.

- cmd/reissueoperator.go
- cmd/reissueoperator_test.go
> Fixed output of nsc reissue operator --convert-to-signing-key

- cmd/pull.go
> Fixed incorrect error message in nsc pull

- .github/workflows/pushes.yaml
- .github/workflows/release.yaml
- .goreleaser.yml
- go.mod
- Adds token configuration for write access to [nats-io/homebrew-nats-tools](https://github.com/nats-io/homebrew-nats-tools)
- Updates GitHub action versions
PR is pending addition of `NATSIO_ARTIFACT_CROSS_REPO_PUSHER_APP_ID` repository secret as well as repository access to the pusher app
> Update Homebrew Release Config

- cmd/edituser.go
- cmd/edituser_test.go
this change ensures that connection types are uppercased, and autofixes any type that is lowercase in an existing JWT
> [FIX] edit user was unable to remove a connection type when in lowercase

- cmd/editscopedsk.go
- cmd/editscopedsk_test.go
This change ensures that connection types are uppercased, and autofixes any type that is lowercase in an existing scoped signing-key.
In reference to #664 
Please review carefully, this is my first contribution to `nsc`.
> [FIX] edit signing-key was unable to remove a connection type when in lowercase

- .goreleaser.yml
Similar to PR https://github.com/nats-io/natscli/pull/1227, but using [Cobra CLI](https://cobra.dev)
> Add completions to Homebrew

- cmd/list.go
- cmd/list_test.go
> [FEAT] allow list operators/accounts/users to show its output as JSON

- cmd/push.go
- cmd/push_test.go
[CHANGE] for accounts that have operators with strict signing keys, if the account only uses scoped signing key - the command will require the system user to be specified, previously it selected the first key, which may or not have the correct permissions.
This update adds comprehensive tests and improved validation logic to handle signing keys when pushing or pulling configurations. The changes ensure proper differentiation between scoped and non-scoped keys and provide clearer error messages when required keys are missing or improperly configured.
Fixes #719
> Add stricter validation for signing keys in push/pull commands

- cmd/add.go
- cmd/delete.go
- cmd/edit.go
- cmd/export.go
- cmd/generate.go
- cmd/list.go
- cmd/load.go
- cmd/tool.go
> enhance cli help
